name: localai_frontend
description: "LocalAI Flutter Frontend Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  go_router: ^13.2.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  sqflite: ^2.3.0
  path: ^1.8.3
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  bloc_test: ^9.1.5
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
